TestMemoryMVC/ViewModels/BaseViewModel.cs
namespace TestMemoryMVC.ViewModels
{
    public class BaseViewModel
    {
        protected bool UseMemoryStorage { get; set; }
    }
}

TestMemoryMVC/ViewModels/ConfigurationViewModel.cs
namespace TestMemoryMVC.ViewModels
{
    public class ConfigurationViewModel : BaseViewModel
    {
        public bool MemoryStrategy { get; set; }

        public string LastUpdate { get; set; }
    }
}

TestMemoryMVC/ViewModels/ProductsViewModel.cs
using System.Collections.Generic;
using TestMemoryMVC.Persistence;

namespace TestMemoryMVC.ViewModels
{
    public class ProductsViewModel
    {

        public ProductsViewModel()
        {
            this.Products = new List<Product>();
        }


        public Product Product { get; set; }

        public List<Product> Products { get; set; }

        public List<Category> Categories { get; set; }


    }
}

TestMemoryMVC/Controllers/CategoriesController.cs
using System.Web.Mvc;

namespace TestMemoryMVC.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        public ActionResult Index()
        {
            return View("List");
        }
    }
}

TestMemoryMVC/Controllers/ConfigurationController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TestMemoryMVC.Persistence.Repositories;
using TestMemoryMVC.ViewModels;

namespace TestMemoryMVC.Controllers
{
    public class ConfigurationController : Controller
    {
        private ConfigurationRepository _conf;

        public ConfigurationController()
        {
            _conf = new ConfigurationRepository();
        }

        public ActionResult Index()
        {
            var viewModel = new ConfigurationViewModel();
            var conf = _conf.GetConfiguration();

            viewModel.MemoryStrategy = (bool)conf.MemoryStrategy;
            viewModel.LastUpdate = conf.MameryStrategyDateChaged.ToString();

            return View("Index", viewModel);
        }


        public ActionResult Save(ConfigurationViewModel viewModel)
        {
            _conf.SaveConfiguration(viewModel.MemoryStrategy);
            return RedirectToAction("Index", "Home");
        }
    }
}

TestMemoryMVC/Controllers/CustomersController.cs
using System.Linq;
using System.Web.Mvc;
using TestMemoryMVC.ViewModels;

namespace TestMemoryMVC.Controllers
{
    public class CustomersController : Controller
    {
        

        // GET: Customers
        public ActionResult Index()
        {
           

            return View("List");
        }
    }
}

TestMemoryMVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TestMemoryMVC.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

TestMemoryMVC/Controllers/OrdersController.cs
using System.Web.Mvc;

namespace TestMemoryMVC.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders
        public ActionResult Index()
        {
            return View("List");
        }
    }
}

TestMemoryMVC/Controllers/ProductsController.cs
using System.Web.Mvc;
using TestMemoryMVC.Persistence;
using TestMemoryMVC.Persistence.Repositories;
using TestMemoryMVC.ViewModels;

namespace TestMemoryMVC.Controllers
{
    public class ProductsController : Controller
    {

        private ProductsRepository _productsRepository;
        private CategoriesRepository _categoryRepository;

        public ProductsController()
        {
            _productsRepository = new ProductsRepository();
            _categoryRepository = new CategoriesRepository();
        }

        public ActionResult Index()
        {
            var viewModel = new ProductsViewModel();

            viewModel.Products = _productsRepository.GetAll();

            return View("List", viewModel);
        }


        public ActionResult New()
        {
            var viewModel = new ProductsViewModel();

            viewModel.Categories = _categoryRepository.GetAll();

            return View("ProductsForm", viewModel);
        }

        public ActionResult Add(Product product)
        {
            var viewModel = new ProductsViewModel();
            
            _productsRepository.Add(product);

            viewModel.Products = _productsRepository.GetAll();

            return View("List", viewModel);
        }
    }
}

TestMemoryMVC/Views/Categories/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>Cetagories</h2>

TestMemoryMVC/Views/Configuration/Index.cshtml
@model TestMemoryMVC.ViewModels.ConfigurationViewModel

@{
    /**/

    ViewBag.Title = "Index";
}

<h2>Web Shop Configuration</h2>

@using (Html.BeginForm("Save", "Configuration"))
{
    <br />
    <br />

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.MemoryStrategy) Database Storage?
        </label>
    </div>

    <div class="form-group">
        
        Last Update on <b>@Model.LastUpdate.ToString()</b>
    </div>


    <button type="submit" class="btn btn-primary">Save</button>

}

TestMemoryMVC/Views/Customers/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>Customers</h2>

TestMemoryMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestMemoryMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestMemoryMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestMemoryMVC/Views/Orders/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>Orders</h2>

TestMemoryMVC/Views/Products/List.cshtml
@model TestMemoryMVC.ViewModels.ProductsViewModel

@{
    ViewBag.Title = "List";
}


<h2>Products</h2>

@if (!Model.Products.Any())
{
    <p>We don't have any products yet.</p>
}
else
{
    <table id="products" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
            <tr>
                <td>@product.Code</td>
                <td>@product.Name</td>
                <td>$@product.Price</td>
            </tr>
            }
        </tbody>
    </table>
}

<br />

<p>
    @Html.ActionLink("New Product", "New", "Products", null, new { @class = "btn btn-primary" })
</p>

TestMemoryMVC/Views/Products/ProductsForm.cshtml
@model TestMemoryMVC.ViewModels.ProductsViewModel

@{
    ViewBag.Title = "Add Product";
}

@using (Html.BeginForm("Add", "Products"))
{
    <br />
    <br />

    <div class="form-group">
        @Html.LabelFor(m => m.Product.Code)
        @Html.TextBoxFor(m => m.Product.Code, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Product.Code)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Product.Name)
        @Html.TextBoxFor(m => m.Product.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Product.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Product.Price)
        @Html.TextBoxFor(m => m.Product.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Product.Price)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Product.Price)
        @Html.DropDownListFor(m => m.Product.CategoryId, new SelectList(Model.Categories, "Id", "Name"), "Select a Category", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Product.CategoryId)
    </div>

    <button type="submit" class="btn btn-primary">Add</button>

}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

TestMemoryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test Products", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>                                        
                    <li>@Html.ActionLink("Configuration", "Index", "Configuration")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>